builds:
  - id: janet
    binary: janet
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
      - CGO_FLAGS=--sysroot=/sysroot/linux/armhf
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/armhf
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/armhf
      - PKG_CONFIG_PATH=/sysroot/linux/armhf/opt/vc/lib/pkgconfig:/sysroot/linux/armhf/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/armhf/usr/lib/pkgconfig:/sysroot/linux/armhf/usr/local/lib/pkgconfig
    main: ./cmd/janet/main.go
    ldflags: -s -w -X "github.com/troyxmccall/janet.Version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
  - id: janetctl
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
      - CGO_FLAGS=--sysroot=/sysroot/linux/armhf
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/armhf
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/armhf
      - PKG_CONFIG_PATH=/sysroot/linux/armhf/opt/vc/lib/pkgconfig:/sysroot/linux/armhf/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/armhf/usr/lib/pkgconfig:/sysroot/linux/armhf/usr/local/lib/pkgconfig
    binary: janetctl
    main: ./cmd/janetctl/main.go
    ldflags: -s -w -X "github.com/troyxmccall/janet.Version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - id: janet
    dockerfile: ./cmd/janet/Dockerfile-goreleaser
    image_templates:
      - "troyxmccall/janet:{{ .Version }}"
      - "troyxmccall/janet:latest"
  - id: janet-webui
    dockerfile: ./cmd/janet/Dockerfile-webui-goreleaser
    image_templates:
      - "troyxmccall/janet:{{ .Version }}-webui"
      - "troyxmccall/janet:latest-webui"
    extra_files:
      - www
  - id: janetctl
    dockerfile: ./cmd/janetctl/Dockerfile-goreleaser
    image_templates:
      - "troyxmccall/janetctl:{{ .Version }}"
      - "troyxmccall/janetctl:latest"
