builds:
  - id: janet
    binary: janet
    main: ./cmd/janet/main.go
    ldflags: -s -w -X "github.com/troyxmccall/janet.Version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
  - id: janetctl
    binary: janetctl
    main: ./cmd/janetctl/main.go
    ldflags: -s -w -X "github.com/troyxmccall/janet.Version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - id: janet
    dockerfile: ./cmd/janet/Dockerfile-goreleaser
    # IDs to filter the binaries/packages.
    ids:
      - janet
    image_templates:
      - "troyxmccall/janet:{{ .Version }}"
      - "troyxmccall/janet:latest"
  - id: janet-webui
    # IDs to filter the binaries/packages.
    ids:
      - janet
    dockerfile: ./cmd/janet/Dockerfile-webui-goreleaser
    image_templates:
      - "troyxmccall/janet:{{ .Version }}-webui"
      - "troyxmccall/janet:latest-webui"
    extra_files:
      - www
  - id: janetctl
    # IDs to filter the binaries/packages.
    ids:
      - janetctl
    dockerfile: ./cmd/janetctl/Dockerfile-goreleaser
    image_templates:
      - "troyxmccall/janetctl:{{ .Version }}"
      - "troyxmccall/janetctl:latest"
