builds:
  - id: janet-server
    binary: janet-server
    main: ./janet-server/main.go
    ldflags: -s -w -X "github.com/troyxmccall/janet.Version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
  - id: janet-bot
    binary: janet-bot
    main: ./cmd/janet-bot/main.go
    ldflags: -s -w -X "github.com/troyxmccall/janet.Version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
  - id: janetctl
    binary: janetctl
    main: ./cmd/janetctl/main.go
    ldflags: -s -w -X "github.com/troyxmccall/janet.Version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - id: janet-server
    dockerfile: ./janet-server/Dockerfile
    # IDs to filter the binaries/packages.
    ids:
      - janet-server
    image_templates:
      - "troyxmccall/janet:{{ .Version }}"
      - "troyxmccall/janet:latest"
  - id: janet-bot
    dockerfile: ./cmd/janet-bot/Dockerfile
    # IDs to filter the binaries/packages.
    ids:
      - janet-bot
    image_templates:
      - "troyxmccall/janet-bot:{{ .Version }}"
      - "troyxmccall/janet-bot:latest"
  - id: janetctl
    # IDs to filter the binaries/packages.
    ids:
      - janetctl
    dockerfile: ./cmd/janetctl/Dockerfile-goreleaser
    image_templates:
      - "troyxmccall/janetctl:{{ .Version }}"
      - "troyxmccall/janetctl:latest"
