# Use the latest Go Alpine image for building
FROM golang:alpine AS build

# Need to mount /var/run/docker.sock
# Need to mount /root/.config/goreleaser/github_token
# Need to mount /go/src/github.com/troyxmccall/janet

RUN apk add --no-cache alpine-sdk git docker

RUN mkdir /tmp/goreleaser && \
    cd /tmp/goreleaser && \
    wget -O goreleaser.tgz https://github.com/goreleaser/goreleaser/releases/download/v1.8.3/goreleaser_Linux_x86_64.tar.gz && \
    tar vxf goreleaser.tgz && \
    mv goreleaser /bin && \
    rm -r /tmp/goreleaser

ENTRYPOINT ["goreleaser"]
